language: python

python: "3.7"
cache: pip

install:
  - pip install -r requirements.txt

script:
  - black -q --check money_bot
  - isort -rc money_bot
  - pylint -E money_bot

after_success:
  - pylint money_bot

deploy:
  - provider: heroku
    api_key: $HEROKU_API_KEY
    app: $HEROKY_DEVELOP
    on:
      branch: develop
  - provider: heroku
    api_key: $HEROKU_API_KEY
    app: $HEROKY_PROD
    on:
      branch: master
