language: python

python: "3.7"
install:
  - pip install -r requirements.txt

script:
  - black -q --check money_bot
  - isort -rc money_bot
  - pylint -E money_bot

after_success:
  - pylint money_bot

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: money-bot-summer-school
  on: 
    branch: develop
