BOT_TOKEN = ""

CLUSTER_NAME = ""
DB_NAME = ""
DB_USER_NAME = ""
DB_USER_PASSWORD = ""
DB_HOST = f"mongodb+srv://{DB_USER_NAME}:{DB_USER_PASSWORD}@{CLUSTER_NAME}/{DB_NAME}?retryWrites=true&w=majority"

MONEY_FOR_GROUP = 20
INVITE_REWARD_MONEY_AMOUNT = 3
