import os

BOT_TOKEN = os.getenv("BOT_TOKEN")

CLUSTER_NAME = ""
DB_NAME = ""
DB_USER_NAME = ""
DB_USER_PASSWORD = ""
DB_HOST = os.getenv("MONGODB_HOST")

JOIN_GROUP_REWARD = 1
REFERRAL_REWARD = 2
REFEREES_TO_ENABLE_WITHDRAWAL = 5
MONEY_AMOUNT_TO_ENABLE_WITHDRAWAL = 100
